// ===========================================================================
// COMMNDO IS DEBUGGER - PLUGIN METADATA & REGISTRATION
// ===========================================================================
// Registers the Commondo IS Debugger plugin metadata, sidebar button,
// and UI5 header toolbar hooks with CPI-Helper.

var plugin = {
  metadataVersion: "1.0.0",
  id: "commondoDebugger",
  name: "Commondo IS Debugger",
  version: "1.0.0",
  author: "Antonio Valec/Commondo",
  website: "https://commondo.eu",
  email: "antonio.valec@commondo.eu",
  description: "Visual multi-tier iFlow debugger with recursive ProcessDirect topology mapping, interactive step payload inspection, and full trace ZIP export.",
  settings: {},

  // Dedicated button in CPI-Helper sidebar panel
  messageSidebarContent: {
    static: true,
    onRender: (pluginHelper, settings) => {
      const container = document.createElement("div");
      container.style.cssText = "margin: 0; padding: 0;";

      const btn = document.createElement("button");
      btn.id = "cmd-sidebar-open-debugger-btn";
      btn.className = "ui fluid mini primary button";
      btn.style.cssText = "font-weight: 600; display: flex; align-items: center; justify-content: center; gap: 6px; padding: 8px 10px; border-radius: 4px; font-size: 0.82rem; background-color: #0070f3;";
      btn.innerHTML = `<i class="sitemap icon" style="margin: 0;"></i> Commondo IS Debugger`;

      btn.onclick = async () => {
        if (typeof CmdDebuggerMainModal !== "undefined") {
          await CmdDebuggerMainModal.openModal(null);
        }
      };

      container.appendChild(btn);

      // Remove the redundant duplicate header generated by CPI-Helper plugin wrapper
      setTimeout(() => {
        const parentArea = document.querySelector("#cpiHelper_messageSidebar_pluginArea_commondoDebugger");
        if (parentArea) {
          const duplicateHeader = parentArea.querySelector(".ui.tiny.header");
          if (duplicateHeader) duplicateHeader.remove();
          parentArea.style.padding = "6px 8px";
          parentArea.style.margin = "0 0 6px 0";
        }
      }, 0);

      return container;
    },
  },

  // Script editor button
  scriptButton: {
    icon: { type: "icon", text: "xe0b6" },
    title: "Commondo IS Debugger",
    onClick: async (pluginHelper, settings) => {
      if (typeof CmdDebuggerMainModal !== "undefined") {
        await CmdDebuggerMainModal.openModal(null);
      }
    },
  },

  // Heartbeat hook to synchronize header Trace IFlows button and check jump tokens
  heartbeat: async (pluginHelper, settings) => {
    if (typeof CmdHeaderTraceButton !== "undefined" && CmdHeaderTraceButton.injectButton) {
      await CmdHeaderTraceButton.injectButton();
    }
    checkPendingInlineTraceJump();
  },
};

// One-shot auto-activation handler for Jump to iFlow with active run instance
async function checkPendingInlineTraceJump() {
  if (typeof window === "undefined") return;
  if (typeof chrome === "undefined" || !chrome.storage || !chrome.storage.local) return;

  chrome.storage.local.get(["cmd_pending_inline_trace"], async (result) => {
    const pending = result ? result.cmd_pending_inline_trace : null;
    if (!pending || !pending.messageGuid) return;

    // 1. Immediately delete from storage so it is strictly one-shot
    try {
      chrome.storage.local.remove(["cmd_pending_inline_trace"]);
    } catch (eDel) {}

    // 2. Discard if older than 45 seconds
    if (pending.timestamp && Date.now() - pending.timestamp > 45000) {
      return;
    }

    const targetGuid = pending.messageGuid;
    const targetFlowId = pending.targetFlowId || "";

    // 3. Verify that current page matches targetFlowId if available
    const targetLow = String(targetFlowId).toLowerCase().trim();
    const activeFlow = (typeof cpiData !== "undefined" && cpiData.integrationFlowId) ? String(cpiData.integrationFlowId).toLowerCase().trim() : "";
    const hrefDecoded = decodeURIComponent(window.location.href).toLowerCase();

    if (targetLow && activeFlow && targetLow !== activeFlow && !hrefDecoded.includes(targetLow)) {
      return;
    }

    // 4. Wait for SAP BPMN SVG canvas to finish rendering and trigger showInlineTrace on the exact run
    let attempts = 0;
    const checkCanvasInterval = setInterval(async () => {
      attempts++;
      const shapes = document.querySelectorAll("[id^='BPMNShape_'], [id^='BPMNEdge_']");
      if (shapes && shapes.length > 0 && typeof showInlineTrace === "function") {
        clearInterval(checkCanvasInterval);
        try {
          if (typeof hideInlineTrace === "function") hideInlineTrace();

          // Mark the exact message in the sidebar as active so clickTrace targets this specific run
          if (typeof activeInlineItem !== "undefined") {
            activeInlineItem = targetGuid;
          }
          const targetBtn = document.querySelector(`.cpiHelper_inlineInfo-button.${targetGuid}`);
          if (targetBtn) {
            document.querySelectorAll(".cpiHelper_inlineInfo-button").forEach((b) => b.classList.remove("cpiHelper_inlineInfo-active"));
            targetBtn.classList.add("cpiHelper_inlineInfo-active");
          }

          const success = await showInlineTrace(targetGuid);
          if (success && typeof showToast === "function") {
            showToast("Inline Trace Activated for Run", targetGuid.substring(0, 8) + "...", "info");
          } else if (!success && typeof showToast === "function") {
            showToast("No trace payloads for this run", "Ensure TRACE logging was enabled", "warning");
          }
        } catch (eTrace) {
          console.warn("[CommondoDebugger] Auto inline trace activation failed:", eTrace);
        }
      } else if (attempts > 60) {
        clearInterval(checkCanvasInterval);
      }
    }, 500);
  });
}

// Auto-register in CPI Helper plugin list
if (typeof pluginList !== "undefined") {
  pluginList.push(plugin);
}

// Initialize top toolbar Trace button and global shortcuts
if (typeof CmdHeaderTraceButton !== "undefined" && CmdHeaderTraceButton.init) {
  CmdHeaderTraceButton.init();
}

// Check for pending jump token on load
if (typeof window !== "undefined") {
  setTimeout(checkPendingInlineTraceJump, 200);

  window.openCommondoDebugger = (runInfo) => {
    if (typeof CmdDebuggerMainModal !== "undefined") {
      CmdDebuggerMainModal.openModal(runInfo);
    }
  };
}
