// ===========================================================================
// COMMNDO IS DEBUGGER - PLUGIN METADATA & REGISTRATION
// ===========================================================================
// Registers the Commondo IS Debugger plugin metadata, sidebar button,
// and UI5 header toolbar hooks with CPI-Helper.

var plugin = {
  metadataVersion: "1.0.0",
  id: "commondoDebugger",
  name: "Commondo IS Debugger",
  version: "3.0.0",
  author: "Commondo",
  website: "https://commondo.eu",
  email: "info@commondo.eu",
  description: "Multi-tier iFlow trace debugger, recursive PD call-chain topology graph & trace exporter.",
  settings: {},

  // Dedicated button in CPI-Helper sidebar panel
  messageSidebarContent: {
    static: true,
    onRender: (pluginHelper, settings) => {
      const container = document.createElement("div");
      container.style.cssText = "margin: 0; padding: 0;";

      const btn = document.createElement("button");
      btn.id = "cmd-sidebar-open-debugger-btn";
      btn.className = "ui fluid mini primary button";
      btn.style.cssText = "font-weight: 600; display: flex; align-items: center; justify-content: center; gap: 6px; padding: 8px 10px; border-radius: 4px; font-size: 0.82rem; background-color: #0070f3;";
      btn.innerHTML = `<i class="sitemap icon" style="margin: 0;"></i> Commondo IS Debugger`;

      btn.onclick = async () => {
        if (typeof CmdDebuggerMainModal !== "undefined") {
          await CmdDebuggerMainModal.openModal(null);
        }
      };

      container.appendChild(btn);

      // Remove the redundant duplicate header generated by CPI-Helper plugin wrapper
      setTimeout(() => {
        const parentArea = document.querySelector("#cpiHelper_messageSidebar_pluginArea_commondoDebugger");
        if (parentArea) {
          const duplicateHeader = parentArea.querySelector(".ui.tiny.header");
          if (duplicateHeader) duplicateHeader.remove();
          parentArea.style.padding = "6px 8px";
          parentArea.style.margin = "0 0 6px 0";
        }
      }, 0);

      return container;
    },
  },


  // Script editor button
  scriptButton: {
    icon: { type: "icon", text: "xe0b6" },
    title: "Commondo IS Debugger",
    onClick: async (pluginHelper, settings) => {
      if (typeof CmdDebuggerMainModal !== "undefined") {
        await CmdDebuggerMainModal.openModal(null);
      }
    },
  },

  // Heartbeat hook to synchronize header Trace IFlows button
  heartbeat: async (pluginHelper, settings) => {
    if (typeof CmdHeaderTraceButton !== "undefined" && CmdHeaderTraceButton.injectButton) {
      await CmdHeaderTraceButton.injectButton();
    }
  },
};

// Auto-register in CPI Helper plugin list
if (typeof pluginList !== "undefined") {
  pluginList.push(plugin);
}

// Initialize top toolbar Trace button and global shortcuts
if (typeof CmdHeaderTraceButton !== "undefined" && CmdHeaderTraceButton.init) {
  CmdHeaderTraceButton.init();
}

if (typeof window !== "undefined") {
  window.openCommondoDebugger = (runInfo) => {
    if (typeof CmdDebuggerMainModal !== "undefined") {
      CmdDebuggerMainModal.openModal(runInfo);
    }
  };
}
