// ===========================================================================
// COMMNDO IS DEBUGGER - PLUGIN METADATA & REGISTRATION
// ===========================================================================
// Registers the Commondo IS Debugger plugin metadata, sidebar button,
// and UI5 header toolbar hooks with CPI-Helper.

var plugin = {
  metadataVersion: "1.0.0",
  id: "commondoDebugger",
  name: "Commondo IS Debugger",
  version: "1.0.0",
  author: "Antonio Valec / Commondo",
  website: "https://commondo.eu",
  email: "antonio.valec@commondo.eu",
  description: "Visual multi-tier iFlow debugger with recursive ProcessDirect topology mapping, interactive step payload inspection, and full trace ZIP export.",
  settings: {
    icon: { type: "icon", src: "/images/commondo - cloud logo.png" },
  },

  // Dedicated button in CPI-Helper sidebar panel
  messageSidebarContent: {
    static: true,
    onRender: (pluginHelper, settings) => {
      const container = document.createElement("div");
      container.style.cssText = "margin: 0; padding: 0;";

      const btn = document.createElement("button");
      btn.id = "cmd-sidebar-open-debugger-btn";
      btn.className = "ui fluid mini primary button";
      btn.style.cssText = "font-weight: 600; display: flex; align-items: center; justify-content: center; gap: 6px; padding: 8px 10px; border-radius: 4px; font-size: 0.82rem; background-color: #0070f3;";
      btn.innerHTML = `<i class="sitemap icon" style="margin: 0;"></i> Commondo IS Debugger`;

      btn.onclick = async () => {
        if (typeof CmdDebuggerMainModal !== "undefined") {
          await CmdDebuggerMainModal.openModal(null);
        }
      };

      container.appendChild(btn);

      // Remove the redundant duplicate header generated by CPI-Helper plugin wrapper
      setTimeout(() => {
        const parentArea = document.querySelector("#cpiHelper_messageSidebar_pluginArea_commondoDebugger");
        if (parentArea) {
          const duplicateHeader = parentArea.querySelector(".ui.tiny.header");
          if (duplicateHeader) duplicateHeader.remove();
          parentArea.style.padding = "6px 8px";
          parentArea.style.margin = "0 0 6px 0";
        }
      }, 0);

      return container;
    },
  },

  // Heartbeat hook to synchronize header Trace IFlows button and check jump tokens
  heartbeat: async (pluginHelper, settings) => {
    if (typeof CmdHeaderTraceButton !== "undefined" && CmdHeaderTraceButton.injectButton) {
      await CmdHeaderTraceButton.injectButton();
    }
    checkPendingInlineTraceJump();
  },
};

// One-shot auto-activation handler for Jump to iFlow with active run instance
let isActivatingInlineTrace = false;
let hasActivatedForTab = false;

async function checkPendingInlineTraceJump() {
  if (isActivatingInlineTrace || hasActivatedForTab || typeof window === "undefined") return;
  if (typeof chrome === "undefined" || !chrome.storage || !chrome.storage.local) return;

  isActivatingInlineTrace = true;

  chrome.storage.local.get(["cmd_pending_jumps"], async (result) => {
    const queue = result ? result.cmd_pending_jumps : null;
    if (!queue || typeof queue !== "object") {
      isActivatingInlineTrace = false;
      return;
    }

    const now = Date.now();
    const activeFlow = typeof cpiData !== "undefined" && cpiData.integrationFlowId ? String(cpiData.integrationFlowId).toLowerCase().trim() : "";
    const hrefDecoded = decodeURIComponent(window.location.href).toLowerCase();

    // Find the matching flow entry for this current tab
    let matchedKey = null;
    let matchedPending = null;

    for (const key of Object.keys(queue)) {
      const entry = queue[key];
      if (!entry || !entry.messageGuid) continue;

      // Discard expired (>30 seconds)
      if (entry.timestamp && now - entry.timestamp > 30000) {
        continue;
      }

      const keyLow = String(key).toLowerCase().trim();
      if ((activeFlow && keyLow === activeFlow) || hrefDecoded.includes(keyLow)) {
        matchedKey = key;
        matchedPending = entry;
        break;
      }
    }

    if (!matchedKey || !matchedPending) {
      isActivatingInlineTrace = false;
      return;
    }

    const targetGuid = matchedPending.messageGuid;

    const removeMatchedKey = () => {
      try {
        chrome.storage.local.get(["cmd_pending_jumps"], (curRes) => {
          const curQueue = curRes?.cmd_pending_jumps || {};
          delete curQueue[matchedKey];
          chrome.storage.local.set({ cmd_pending_jumps: curQueue });
        });
      } catch (e) {
        console.warn("[CommondoDebugger] Failed to remove matched jump key:", e);
      }
    };

    const tryActivate = async () => {
      const shapes = document.querySelectorAll("[id^='BPMNShape_'], [id^='BPMNEdge_']");
      if (shapes && shapes.length > 0 && typeof showInlineTrace === "function") {
        try {
          // Mark matching sidebar button as active, or inject hidden holder for older runs outside top 10
          if (typeof activeInlineItem !== "undefined") {
            activeInlineItem = targetGuid;
          }
          document.querySelectorAll(".cpiHelper_inlineInfo-button").forEach((b) => b.classList.remove("cpiHelper_inlineInfo-active"));

          const targetBtn = document.querySelector(`.cpiHelper_inlineInfo-button.${targetGuid}`);
          if (targetBtn) {
            targetBtn.classList.add("cpiHelper_inlineInfo-active");
          } else {
            let holder = document.getElementById("cmd-inline-active-holder");
            if (!holder) {
              holder = document.createElement("div");
              holder.id = "cmd-inline-active-holder";
              holder.style.display = "none";
              document.body.appendChild(holder);
            }
            holder.className = `${targetGuid} cpiHelper_inlineInfo-button cpiHelper_inlineInfo-active`;
          }

          const success = await showInlineTrace(targetGuid);
          hasActivatedForTab = true;
          if (success && typeof showToast === "function") {
            showToast("Inline Trace Activated", `Run ID: ${targetGuid.substring(0, 8)}...`, "info");
          }
        } catch (eTrace) {
          console.warn("[CommondoDebugger] Auto inline trace activation failed:", eTrace);
        } finally {
          removeMatchedKey();
          isActivatingInlineTrace = false;
        }
        return true;
      }
      return false;
    };

    // Sequential non-overlapping async poll for canvas readiness (up to 30s: 75 attempts x 400ms)
    let attempts = 0;
    const pollCanvas = async () => {
      attempts++;
      const done = await tryActivate();
      if (done) return;
      if (attempts < 75) {
        setTimeout(pollCanvas, 400);
      } else {
        removeMatchedKey();
        isActivatingInlineTrace = false;
      }
    };

    pollCanvas();
  });
}

// Auto-register in CPI Helper plugin list
if (typeof pluginList !== "undefined") {
  pluginList.push(plugin);
}

// Initialize top toolbar Trace button and global shortcuts
if (typeof CmdHeaderTraceButton !== "undefined" && CmdHeaderTraceButton.init) {
  CmdHeaderTraceButton.init();
}

// Check for pending jump token on load
if (typeof window !== "undefined") {
  setTimeout(checkPendingInlineTraceJump, 200);

  window.openCommondoDebugger = (runInfo) => {
    if (typeof CmdDebuggerMainModal !== "undefined") {
      CmdDebuggerMainModal.openModal(runInfo);
    }
  };
}
